Feature/atl 295
pagarme/saphire pull request #18
Opened 2021-01-11 17:35 UTC by brunoflegler

.

2021-01-11 19:38 UTC, fabiano-amaral approved these changes

2021-01-11 19:38 UTC, fabiano-amaral commented on .travis.yml
> -  - "0.11"
wat? a gente tava nessa versão no travis?

2021-01-11 19:38 UTC, fabiano-amaral commented on package.json
> -    "setflags": "0.0.2",
que pessoa incrível! menos uma lib hahaha

2021-01-11 19:43 UTC, samycici approved these changes

2021-01-11 19:43 UTC, murilohns approved these changes

2021-01-11 19:57 UTC, kaic approved these changes

2021-01-12 16:31 UTC, trajanoreuter requested changes

2021-01-12 16:31 UTC, trajanoreuter commented on .travis.yml
> +  - 12.0.0
Dados os problemas relatados, sugiro a versão `12.20.1`
https://github.com/nodejs/node/releases/tag/v12.20.1

2021-01-12 19:13 UTC, brunoflegler commented on .travis.yml
> -  - "0.11"
@fabiano-amaral para ser sincero, esse arquivo nem está configurado pra executar nada no travis. Acha que deveriamos remover?

2021-01-12 19:15 UTC, brunoflegler commented on .travis.yml
> +  - 12.0.0
Alterado

2021-01-12 19:15 UTC, fabiano-amaral commented on .travis.yml
> -  - "0.11"
Não tenho opinião sobre o assunto @brunoflegler

2021-01-13 12:40 UTC, trajanoreuter approved these changes

2021-01-19 00:32 UTC, mccraveiro commented
Saphire está sendo ressuscitado 😱

2021-01-19 00:45 UTC, flyingluscas approved these changes

2021-01-19 00:49 UTC, oliveira approved these changes
LGTM

2021-01-19 00:51 UTC, otaviopace approved these changes
bom

2021-01-19 00:58 UTC, ahmarcia approved these changes
🔝

2021-01-19 01:00 UTC, MarcoWorms approved these changes

2021-01-19 01:00 UTC, LeoNero approved these changes

2021-01-19 01:01 UTC, lucasjs approved these changes

2021-01-19 01:03 UTC, mccraveiro approved these changes
💯

2021-01-19 01:04 UTC, wilkmaia approved these changes

2021-01-19 01:05 UTC, uselessdev approved these changes
amaze

2021-01-19 01:05 UTC, moog approved these changes

2021-01-19 01:07 UTC, derekstavis commented
I'm curious if this change will have the same effect as of calling `%SetCode`, if so, could you provide any relevant documentation? I'd love to learn more about this!

2021-01-19 01:08 UTC, IvanMicai approved these changes
LGTM

2021-01-19 01:09 UTC, alalbux approved these changes

2021-01-19 01:09 UTC, uselessdev commented
oi @derekstavis

2021-01-19 01:18 UTC, itsdaiego approved these changes
QUANTA GENTE SUPIMPAAAAAAAAAAAAAA :heart: 

joguem xadrez pessoal, faz bem pro célebru

2021-01-19 01:24 UTC, igorantun approved these changes

2021-01-19 01:32 UTC, miglsoares approved these changes

2021-01-19 05:27 UTC, macabeus approved these changes
💯

2021-01-19 05:30 UTC, macabeus requested changes
nitpick: Creio que o segundo commit deveria ser `chore: remove serflag`, para seguir o padrão constado no item 3.2 do https://github.com/pagarme/git-style-guide

2021-01-19 11:24 UTC, Deivis approved these changes

2021-01-19 14:00 UTC, 0xkalvin approved these changes

2021-01-19 14:00 UTC, Thor99 commented
:heart_eyes: quanta gente maravilhosa :heart:

2021-01-19 15:21 UTC, victorteodoro commented
Flash from the past :sweat_drops:

2021-01-19 16:00 UTC, alalbux commented
saudade desse timão ❤️

2021-02-11 12:31 UTC, merged